#!/usr/bin/env python3
"""
ILMA_FELO_FREE: PPT Generator
Generates PowerPoint presentations from topic/outline using python-pptx.
100% free, no API key needed.
"""

import sys
import os

def make_ppt(topic: str, output_path: str, theme: str = "professional") -> str:
    """Generate PPT from topic string."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RgbColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        return "ERROR: python-pptx not installed. Run: pip install python-pptx --break-system-packages"
    
    # Parse topic into slides
    lines = topic.strip().split('\n')
    
    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)
    
    themes = {
        "professional": {
            "title_color": RgbColor(0, 51, 102),
            "body_color": RgbColor(51, 51, 51),
            "bg_color": RgbColor(255, 255, 255),
            "font": "Arial"
        },
        "modern": {
            "title_color": RgbColor(0, 102, 204),
            "body_color": RgbColor(68, 68, 68),
            "bg_color": RgbColor(245, 245, 245),
            "font": "Calibri"
        },
        "dark": {
            "title_color": RgbColor(255, 255, 255),
            "body_color": RgbColor(200, 200, 200),
            "bg_color": RgbColor(30, 30, 30),
            "font": "Segoe UI"
        },
        "minimal": {
            "title_color": RgbColor(0, 0, 0),
            "body_color": RgbColor(100, 100, 100),
            "bg_color": RgbColor(255, 255, 255),
            "font": "Helvetica"
        }
    }
    
    t = themes.get(theme, themes["professional"])
    
    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    
    # Title text box
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(2.5), Inches(12), Inches(1.5))
    tf = title_box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = lines[0] if lines else topic[:50]
    p.font.size = Pt(44)
    p.font.bold = True
    p.font.name = t["font"]
    p.alignment = PP_ALIGN.CENTER
    
    # Subtitle
    sub_box = slide.shapes.add_textbox(Inches(0.5), Inches(4.2), Inches(12), Inches(1))
    tf2 = sub_box.text_frame
    p2 = tf2.paragraphs[0]
    p2.text = f"Generated by ILMA FELO-FREE | {theme.upper()} Theme"
    p2.font.size = Pt(18)
    p2.font.name = t["font"]
    p2.font.color.rgb = RgbColor(128, 128, 128)
    p2.alignment = PP_ALIGN.CENTER
    
    # Content slides
    for i, line in enumerate(lines[1:]):
        if not line.strip():
            continue
        
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        title_shape = slide.shapes.title
        
        # Section number slide
        if line.strip().startswith("#"):
            title_shape.text = f"Section {i+1}"
            content = slide.placeholders[1]
            tf = content.text_frame
            tf.text = line.lstrip('#').strip()
            tf.paragraphs[0].font.size = Pt(28)
        else:
            # Check for bullet point marker
            if line.strip().startswith(('- ', '* ', '• ')):
                title_shape.text = f"Point {i+1}"
                content = slide.placeholders[1]
                tf = content.text_frame
                tf.text = line.lstrip('- *•').strip()
                tf.paragraphs[0].font.size = Pt(24)
            else:
                title_shape.text = f"Section {i+1}"
                content = slide.placeholders[1]
                tf = content.text_frame
                tf.text = line.strip()
                tf.paragraphs[0].font.size = Pt(24)
    
    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else '.', exist_ok=True)
    
    prs.save(output_path)
    size = os.path.getsize(output_path)
    return f"SUCCESS: PPT saved to {output_path} ({size:,} bytes), {len(lines)} slides generated"