#!/usr/bin/env python3
"""
ILMA Blue Team Rules v1.0
Security rule generation - YARA rules, Suricata rules, threat detection.
Mimics ILMA's blue_team_rules.py functionality.
"""
import re
import json
import hashlib
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@dataclass
class ThreatPattern:
    """A detected threat pattern."""
    id: str
    name: str
    description: str
    pattern: str
    severity: str  # low, medium, high, critical
    category: str
    mitre_attack: Optional[str] = None  # MITRE ATT&CK technique ID
    created_at: datetime = field(default_factory=datetime.now)

@dataclass
class Baseline:
    """System baseline for comparison."""
    id: str
    name: str
    description: str
    checks: List[Dict]
    created_at: datetime = field(default_factory=datetime.now)

class BlueTeamRules:
    """
    Blue Team Rules for ILMA - security rules, YARA/Suricata generation, threat detection.
    """
    
    def __init__(self, storage_dir: str = 'memory/security'):
        self.storage_dir = Path(storage_dir)
        self.storage_dir.mkdir(parents=True, exist_ok=True)
        self.baselines: Dict[str, Baseline] = {}
        self.threat_patterns: List[ThreatPattern] = []
        self.load()
    
    def load(self):
        """Load baselines and patterns."""
        baselines_file = self.storage_dir / 'baselines.json'
        patterns_file = self.storage_dir / 'patterns.json'
        
        if baselines_file.exists():
            try:
                data = json.loads(baselines_file.read_text())
                for b in data.get('baselines', []):
                    self.baselines[b['id']] = Baseline(
                        id=b['id'],
                        name=b['name'],
                        description=b['description'],
                        checks=b['checks'],
                        created_at=datetime.fromisoformat(b['created_at'])
                    )
            except Exception as e:
                logger.error(f"Error loading baselines: {e}")
        
        if patterns_file.exists():
            try:
                data = json.loads(patterns_file.read_text())
                self.threat_patterns = [
                    ThreatPattern(
                        id=p['id'],
                        name=p['name'],
                        description=p['description'],
                        pattern=p['pattern'],
                        severity=p['severity'],
                        category=p['category'],
                        mitre_attack=p.get('mitre_attack'),
                        created_at=datetime.fromisoformat(p['created_at'])
                    ) for p in data.get('patterns', [])
                ]
            except Exception as e:
                logger.error(f"Error loading patterns: {e}")
    
    def save(self):
        """Save baselines and patterns."""
        baselines_file = self.storage_dir / 'baselines.json'
        patterns_file = self.storage_dir / 'patterns.json'
        
        baselines_data = {
            'baselines': [
                {
                    'id': b.id,
                    'name': b.name,
                    'description': b.description,
                    'checks': b.checks,
                    'created_at': b.created_at.isoformat()
                } for b in self.baselines.values()
            ]
        }
        baselines_file.write_text(json.dumps(baselines_data, indent=2))
        
        patterns_data = {
            'patterns': [
                {
                    'id': p.id,
                    'name': p.name,
                    'description': p.description,
                    'pattern': p.pattern,
                    'severity': p.severity,
                    'category': p.category,
                    'mitre_attack': p.mitre_attack,
                    'created_at': p.created_at.isoformat()
                } for p in self.threat_patterns
            ]
        }
        patterns_file.write_text(json.dumps(patterns_data, indent=2))
    
    # ─── YARA Rule Generation ─────────────────────────────────────────────────
    
    def generate_yara_rules(self, pattern: ThreatPattern) -> str:
        """Generate YARA rule from threat pattern."""
        rule_name = re.sub(r'[^a-zA-Z0-9_]', '_', pattern.name)
        
        yara = f"""/*
    YARA Rule: {pattern.name}
    Generated by ILMA Blue Team
    Category: {pattern.category}
    Severity: {pattern.severity}
    MITRE ATT&CK: {pattern.mitre_attack or 'N/A'}
    Date: {datetime.now().isoformat()}
*/

rule {rule_name}
{{
    meta:
        description = "{pattern.description}"
        severity = "{pattern.severity}"
        category = "{pattern.category}"
        mitre_attack = "{pattern.mitre_attack or 'N/A'}"
        author = "ILMA Blue Team"
        date = "{datetime.now().strftime('%Y-%m-%d')}"
    
    strings:
        // Pattern detection
        $pattern1 = "{pattern.pattern}" nocase
        
        // Additional context markers
        $marker1 = "{pattern.category.lower()}" nocase
        $marker2 = "{pattern.name.lower()}" nocase
    
    condition:
        // Primary pattern match
        $pattern1
        
        // Context verification (2 of 3 markers)
        (#marker1 + #marker2) >= 2
}}
"""
        return yara
    
    def generate_yara_rule_set(self, category: str = None) -> str:
        """Generate complete YARA rule set."""
        rules = []
        patterns = self.threat_patterns
        if category:
            patterns = [p for p in patterns if p.category == category]
        
        for pattern in patterns:
            rules.append(self.generate_yara_rules(pattern))
        
        header = f"""/*
    ILMA Blue Team YARA Rules
    Generated: {datetime.now().isoformat()}
    Total Rules: {len(rules)}
    Category: {category or 'ALL'}
*/

import "console"

"""
        return header + "\n\n".join(rules)
    
    # ─── Suricata Rule Generation ──────────────────────────────────────────────
    
    def generate_suricata_rules(self, pattern: ThreatPattern) -> str:
        """Generate Suricata rule from threat pattern."""
        # Map severity to Suricata action
        severity_map = {
            'critical': 'alert',
            'high': 'alert',
            'medium': 'alert',
            'low': 'notice',
        }
        action = severity_map.get(pattern.severity, 'alert')
        
        # Generate simple pattern for Suricata
        safe_pattern = re.sub(r'[^a-zA-Z0-9\s]', '', pattern.pattern)[:50]
        
        suricata = f"""# Alert: {pattern.name}
# Category: {pattern.category}
# Severity: {pattern.severity}
# MITRE: {pattern.mitre_attack or 'N/A'}
{action} tcp any any -> any any (msg:"{pattern.name}"; content:"{safe_pattern}"; nocase; sid:{hashlib.md5(pattern.id.encode()).hexdigest()[:10]}; rev:1;)
"""
        return suricata
    
    def generate_suricata_rule_set(self) -> str:
        """Generate complete Suricata rule set."""
        rules = [self.generate_suricata_rules(p) for p in self.threat_patterns]
        
        header = f"""# ILMA Blue Team Suricata Rules
# Generated: {datetime.now().isoformat()}
# Total Rules: {len(rules)}

# Classification config
# config classification: {rule_name},{pattern.description},{pattern.severity}

"""
        return header + "\n".join(rules)
    
    # ─── Baseline Management ────────────────────────────────────────────────────
    
    def create_baseline(self, name: str, description: str, checks: List[Dict]) -> str:
        """Create a new baseline."""
        baseline_id = hashlib.md5(f"{name}{datetime.now().isoformat()}".encode()).hexdigest()[:12]
        baseline = Baseline(
            id=baseline_id,
            name=name,
            description=description,
            checks=checks,
            created_at=datetime.now()
        )
        self.baselines[baseline_id] = baseline
        self.save()
        return baseline_id
    
    def check_baseline(self, baseline_id: str, current_state: Dict) -> Dict[str, Any]:
        """Check current state against baseline."""
        if baseline_id not in self.baselines:
            return {'error': 'Baseline not found'}
        
        baseline = self.baselines[baseline_id]
        results = []
        passed = 0
        failed = 0
        
        for check in baseline.checks:
            check_type = check.get('type')
            expected = check.get('expected')
            
            if check_type == 'value':
                actual = current_state.get(check.get('field'))
                match = actual == expected
            elif check_type == 'exists':
                actual = current_state.get(check.get('field'))
                match = actual is not None
            elif check_type == 'range':
                actual = current_state.get(check.get('field'))
                min_val = check.get('min')
                max_val = check.get('max')
                match = min_val <= actual <= max_val
            else:
                match = False
            
            results.append({
                'check': check.get('name', 'Unnamed'),
                'passed': match,
                'expected': expected,
                'actual': current_state.get(check.get('field'))
            })
            
            if match:
                passed += 1
            else:
                failed += 1
        
        return {
            'baseline': baseline.name,
            'total': len(results),
            'passed': passed,
            'failed': failed,
            'results': results,
            'compliant': failed == 0
        }
    
    # ─── Threat Detection ─────────────────────────────────────────────────────
    
    def detect_threats(self, text: str) -> List[Dict]:
        """Detect threats in text using patterns."""
        detected = []
        
        for pattern in self.threat_patterns:
            if re.search(pattern.pattern, text, re.IGNORECASE):
                detected.append({
                    'pattern_id': pattern.id,
                    'name': pattern.name,
                    'severity': pattern.severity,
                    'category': pattern.category,
                    'mitre_attack': pattern.mitre_attack,
                    'match': re.search(pattern.pattern, text, re.IGNORECASE).group(0)[:100]
                })
        
        return detected
    
    def add_threat_pattern(self, name: str, description: str, pattern: str,
                           severity: str, category: str, mitre_attack: str = None) -> str:
        """Add a new threat pattern."""
        pattern_id = hashlib.md5(f"{name}{datetime.now().isoformat()}".encode()).hexdigest()[:12]
        threat = ThreatPattern(
            id=pattern_id,
            name=name,
            description=description,
            pattern=pattern,
            severity=severity,
            category=category,
            mitre_attack=mitre_attack,
            created_at=datetime.now()
        )
        self.threat_patterns.append(threat)
        self.save()
        return pattern_id
    
    # ─── Default Patterns ──────────────────────────────────────────────────────
    
    def init_default_patterns(self):
        """Initialize with common threat patterns."""
        default_patterns = [
            {
                'name': 'SQL Injection Attempt',
                'description': 'Potential SQL injection attack',
                'pattern': r"(?:union\s+select|exec\s*\(|;\s*drop\s+table|--|\'OR\s+\'1\'\=\'1)",
                'severity': 'high',
                'category': 'injection',
                'mitre_attack': 'T1005'
            },
            {
                'name': 'XSS Attempt',
                'description': 'Potential cross-site scripting attack',
                'pattern': r"(?:<script|javascript:|onerror\s*=|onload\s*=|<iframe)",
                'severity': 'high',
                'category': 'xss',
                'mitre_attack': 'T1003'
            },
            {
                'name': 'Command Injection Attempt',
                'description': 'Potential command injection attack',
                'pattern': r"(?:;\s*cat\s+|;\s*ls\s+|;\s*pwd|\|\s*nc\s+|&\s*wget\s+)",
                'severity': 'critical',
                'category': 'injection',
                'mitre_attack': 'T1005'
            },
            {
                'name': 'Path Traversal Attempt',
                'description': 'Potential directory traversal attack',
                'pattern': r"(?:\.\.\/|\.\.\\|%2e%2e%2f)",
                'severity': 'high',
                'category': 'traversal',
                'mitre_attack': 'T1005'
            },
            {
                'name': 'Brute Force Indicator',
                'description': 'Potential brute force login attempt',
                'pattern': r"(?:failed\s+login|invalid\s+password|authentication\s+failure)",
                'severity': 'medium',
                'category': 'auth',
                'mitre_attack': 'T1110'
            },
            {
                'name': 'Malware File Indicator',
                'description': 'Known malware file pattern',
                'pattern': r"(?:\.exe\s*$|\.dll\s*$|\.vbs\s*$|\.bat\s*$|\.ps1\s*$)",
                'severity': 'high',
                'category': 'malware',
                'mitre_attack': 'T1003'
            },
            {
                'name': 'Data Exfiltration Indicator',
                'description': 'Potential data exfiltration attempt',
                'pattern': r"(?:sensitive|confidential|secret| classified |proprietary)",
                'severity': 'medium',
                'category': 'exfiltration',
                'mitre_attack': 'T1041'
            },
            {
                'name': 'Cryptomining Indicator',
                'description': 'Potential cryptomining activity',
                'pattern': r"(?:stratum\+tcp|coinbase|cryptonight|xmrig|monero)",
                'severity': 'high',
                'category': 'cryptomining',
                'mitre_attack': 'T1496'
            }
        ]
        
        for p in default_patterns:
            self.add_threat_pattern(**p)
        
        logger.info(f"Initialized {len(default_patterns)} default threat patterns")
    
    def export_rules(self, format: str = 'yara', output_file: str = None) -> str:
        """Export rules in specified format."""
        if format == 'yara':
            content = self.generate_yara_rule_set()
        elif format == 'suricata':
            content = self.generate_suricata_rule_set()
        elif format == 'json':
            content = json.dumps({
                'patterns': [
                    {
                        'id': p.id,
                        'name': p.name,
                        'description': p.description,
                        'pattern': p.pattern,
                        'severity': p.severity,
                        'category': p.category,
                        'mitre_attack': p.mitre_attack
                    } for p in self.threat_patterns
                ]
            }, indent=2)
        else:
            content = ""
        
        if output_file:
            Path(output_file).write_text(content)
            logger.info(f"Exported {len(self.threat_patterns)} rules to {output_file}")
        
        return content
    
    def health_check(self) -> dict:
        """Health endpoint."""
        return {
            "ok": True,
            "module": "blue_team_rules",
            "patterns": len(self.threat_patterns),
            "baselines": len(self.baselines),
            "categories": list(set(p.category for p in self.threat_patterns))
        }

if __name__ == '__main__':
    bt = BlueTeamRules()
    
    print("="*60)
    print("ILMA Blue Team Rules - Test")
    print("="*60)
    
    # Initialize default patterns
    bt.init_default_patterns()
    
    # Test threat detection
    test_logs = [
        "User attempted ' OR '1'='1 in login form",
        "Suspicious file downloaded: malicious.exe",
        "Normal user activity logged",
    ]
    
    print("\n[1] Threat Detection:")
    for log in test_logs:
        threats = bt.detect_threats(log)
        if threats:
            for t in threats:
                print(f"  [!] {t['name']} ({t['severity']})")
        else:
            print(f"  [OK] Clean: {log[:40]}...")
    
    print(f"\n[2] YARA Rule Sample:")
    if bt.threat_patterns:
        yara = bt.generate_yara_rules(bt.threat_patterns[0])
        print(yara[:300] + "...")
    
    print(f"\n[3] Stats: {bt.health_check()}")
    print("\n[✅] Blue Team Rules operational")
