#!/usr/bin/env python3
"""
ILMA FREE SLIDES — Native PPT Generator (100% FREE)
Replaces: felo-slides (API felo.ai)

HOW IT WORKS:
  1. python-pptx library → generates real .pptx files
  2. Takes topic/title as input
  3. Generates structured slides with title, content, bullets
  4. Output: .pptx file (LibreOffice/Google Slides compatible)

USAGE:
  python3 ilma_free_slides.py "AI Trends 2025" --slides 10 --output /tmp/ai_slides.pptx

REQUIREMENTS:
  - python-pptx (already installed)
"""

import sys
import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN


def create_presentation(
    title: str,
    num_slides: int = 8,
    output_path: str = None
) -> str:
    """
    Generate a PPTX presentation from a topic.
    Returns path to the generated file.
    """
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Slide layout: 0=title, 1=title+content, 6=blank
    title_slide_layout = prs.slide_layouts[0]
    content_slide_layout = prs.slide_layouts[1]

    # --- Slide 1: Title Slide ---
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    subtitle_shape = slide.placeholders[1]

    title_shape.text = title
    subtitle_shape.text = "Generated by ILMA • Free PPT Generator"

    # Style title
    title_frame = title_shape.text_frame
    title_para = title_frame.paragraphs[0]
    title_para.font.size = Pt(44)
    title_para.font.bold = True
    title_para.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)
    title_para.alignment = PP_ALIGN.CENTER

    # --- Content Slides ---
    slide_topics = generate_slide_outline(title, num_slides - 1)

    for topic, bullets in slide_topics:
        slide = prs.slides.add_slide(content_slide_layout)
        title_shape = slide.shapes.title
        body_shape = slide.placeholders[1]

        title_shape.text = topic

        # Style title
        tf = title_shape.text_frame
        p = tf.paragraphs[0]
        p.font.size = Pt(32)
        p.font.bold = True
        p.font.color.rgb = RGBColor(0x16, 0x21, 0x3e)

        # Fill body
        tf = body_shape.text_frame
        tf.clear()
        for bullet in bullets:
            p = tf.add_paragraph()
            p.text = f"• {bullet}"
            p.level = 0
            p.font.size = Pt(20)
            p.font.color.rgb = RGBColor(0x2d, 0x2d, 0x44)
            p.space_before = Pt(6)

    # --- Final Slide: Summary ---
    slide = prs.slides.add_slide(content_slide_layout)
    title_shape = slide.shapes.title
    body_shape = slide.placeholders[1]
    title_shape.text = "Summary"
    tf = title_shape.text_frame
    p = tf.paragraphs[0]
    p.font.size = Pt(32)
    p.font.bold = True

    tf = body_shape.text_frame
    tf.clear()
    p = tf.add_paragraph()
    p.text = f"📌 Topic: {title}"
    p.font.size = Pt(22)
    p.space_before = Pt(10)

    p = tf.add_paragraph()
    p.text = f"📊 Total Slides: {num_slides}"
    p.font.size = Pt(22)

    p = tf.add_paragraph()
    p.text = "✅ Generated 100% Free — ILMA Native PPT Generator"
    p.font.size = Pt(20)
    p.font.italic = True
    p.font.color.rgb = RGBColor(0x00, 0x80, 0x00)

    # Save
    if not output_path:
        safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in title)
        safe_name = safe_name[:50].strip()
        output_path = f"/tmp/ILMA_{safe_name}.pptx"

    prs.save(output_path)
    return output_path


def generate_slide_outline(title: str, num_slides: int) -> list:
    """
    Generate slide topics and bullets from a title.
    This is a simple rule-based generator.
    For better results, combine with search tool first.
    """
    base = title.strip()

    templates = [
        ("Overview", [
            f"Introduction to {base}",
            "Why this topic matters today",
            "Key challenges and opportunities",
            "Target audience and scope"
        ]),
        ("Background & Context", [
            "Historical context and evolution",
            "Current state of the industry",
            "Major stakeholders and players",
            "Recent developments (2024-2025)"
        ]),
        ("Key Concepts", [
            "Core principles and fundamentals",
            "Important terminology",
            "How it works: step by step",
            "Common misconceptions"
        ]),
        ("Benefits & Advantages", [
            "Primary benefits for users/stakeholders",
            "Efficiency gains and cost savings",
            "Quality improvements",
            "Competitive advantages"
        ]),
        ("Challenges & Risks", [
            "Technical challenges and hurdles",
            "Security and privacy concerns",
            "Regulatory considerations",
            "Resource requirements"
        ]),
        ("Use Cases & Applications", [
            "Industry-specific applications",
            "Real-world case studies",
            "Success stories and examples",
            "Emerging use cases"
        ]),
        ("Market Landscape", [
            "Key players and vendors",
            "Market size and growth trends",
            "Investment and funding landscape",
            "Regional variations"
        ]),
        ("Future Outlook", [
            "Predicted trends for 2025-2030",
            "Upcoming innovations and breakthroughs",
            "How to prepare and adapt",
            "Call to action: next steps"
        ]),
        ("Implementation Guide", [
            "Getting started: prerequisites",
            "Step-by-step implementation",
            "Best practices and tips",
            "Common pitfalls to avoid"
        ]),
        ("Tools & Technologies", [
            "Recommended tools and platforms",
            "Open source vs proprietary",
            "Integration considerations",
            "Learning resources and communities"
        ]),
    ]

    # Select slides based on num_slides
    selected = templates[:min(num_slides, len(templates))]

    # If we need more slides, extend the last template
    while len(selected) < num_slides:
        last_topic = selected[-1][0]
        selected.append((f"More on {last_topic}", ["Additional insights", "Supporting data", "Related considerations"]))

    return selected


def format_slides_output(file_path: str, title: str, num_slides: int) -> str:
    """Format the result as markdown."""
    size = os.path.getsize(file_path)
    size_kb = size / 1024

    return f"""## ✅ PPT Generated Successfully!

📊 **Details:**
- **Topic:** {title}
- **Slides:** {num_slides}
- **File:** `{file_path}`
- **Size:** {size_kb:.1f} KB
- **Status:** Ready to open in PowerPoint, Google Slides, or LibreOffice

🔗 **Download/Share:** Transfer the file from `{file_path}` to your device.

💡 **Tip:** For better content, provide a URL or detailed outline when calling the generator.
"""


if __name__ == "__main__":
    title = ""
    num_slides = 8
    output_path = None

    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--slides" and i + 1 < len(args):
            num_slides = int(args[i + 1])
            i += 2
        elif args[i] == "--output" and i + 1 < len(args):
            output_path = args[i + 1]
            i += 2
        else:
            title += (" " + args[i]) if title else args[i]
            i += 1

    if not title:
        print("Usage: python3 ilma_free_slides.py <title> [--slides N] [--output path.pptx]")
        sys.exit(1)

    file_path = create_presentation(title.strip(), num_slides, output_path)
    print(format_slides_output(file_path, title, num_slides))
